export const HOME = '/'
export const UPLOAD = '/pictures/upload'
export const SIGN_UP = '/auth/signup'
export const LOG_IN = '/auth/login'
export const PICTURE = '/pictures/:picId'
export const SERVER_BASE_URL = 'http://localhost:8080'
export const EDIT_PROFILE = '/accounts/edit'
