export const HOME = '/'
export const UPLOAD = '/pictures/upload'
export const SIGN_UP = '/auth/signup'
export const LOG_IN = '/auth/login'
export const ERROR = '/error'
export const PICTURE = '/pictures/:id'
