export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Picture } from './Picture'
export { default as Upload } from './Upload'
export { default as Error } from './Error'
export { default as Profile } from './Profile'
export { default as EditProfile } from './EditProfile'
